### ISSUE TITLE
Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [cyrixmorten/GuildColor#1]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by cyrixmorten** [comment]
Hi @maximus210793 

This is a variant of an existing GuildColors addon that I made for a friend who at the time played classic WoW on a private server.

I do not play the game so cannot debug what it would take to make it compatible, think chances are higher to get the devs of the original addon to update it.

Looks like you commented there too so hope they pick it up :)

https://www.curseforge.com/wow/addons/guildcolors/
